### ISSUE TITLE
Raqm error?

### ISSUE THREAD

**Issue by IsNaRm** [Conradk10/tonRocket-captcha-solver#1]
![image](https://user-images.githubusercontent.com/11133034/217506468-31157a28-f4ca-4a06-b9d3-a458ac1a5c5d.png)

how to solve?

**Comment by Conradk10** [comment]
In file `utils.py`, in line 12 change font size from 109 to 137.
example:
from: `fnt = ImageFont.truetype("AppleColorEmoji.ttf", size=109, layout_engine=ImageFont.Layout.RAQM)`
to: `fnt = ImageFont.truetype("AppleColorEmoji.ttf", size=137, layout_engine=ImageFont.Layout.RAQM)`
or just clone the new updated version of script.
